# .readthedocs.yml

version: 2

build:
  image: latest

python:
  version: 3.6
  setup_py_install: true
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .
  system_packages: true
